SELECT * FROM pr2.PersonStatus;
SELECT * FROM pr2.Addresses;
SELECT * FROM pr2.Person;
SELECT * FROM pr2.StudentStatus;
SELECT * FROM pr2.Students;
SELECT * FROM pr2.Colleges;
SELECT * FROM pr2.ProgramOfStudy;
SELECT * FROM pr2.Majors;
SELECT * FROM pr2.Minors;
SELECT * FROM pr2.BenefitsSelection;
SELECT * FROM pr2.HealthBenefits;
SELECT * FROM pr2.VisionBenefits;
SELECT * FROM pr2.DentalBenefits;
SELECT * FROM pr2.JobInformation;
SELECT * FROM pr2.Employees;
SELECT * FROM pr2.Courses;
SELECT * FROM pr2.Prerequisites;
SELECT * FROM pr2.Semester;
SELECT * FROM pr2.SemesterInfo;
SELECT * FROM pr2.BuildingName;
SELECT * FROM pr2.Location;
SELECT * FROM pr2.Projector;
SELECT * FROM pr2.Classroom;
SELECT * FROM pr2.ScheduledCourses;
SELECT * FROM pr2.DailyCourseDay;
SELECT * FROM pr2.EnrollmentStatus;
SELECT * FROM pr2.StudentGrade;
SELECT * FROM pr2.Enrollment;

DROP TABLE pr2.PersonStatus;
DROP TABLE pr2.Addresses;
DROP TABLE pr2.Person;
DROP TABLE pr2.StudentStatus;
DROP TABLE pr2.Students;
DROP TABLE pr2.Colleges;
DROP TABLE pr2.ProgramOfStudy;
DROP TABLE pr2.Majors;
DROP TABLE pr2.Minors;
DROP TABLE pr2.BenefitsSelection;
DROP TABLE pr2.HealthBenefits;
DROP TABLE pr2.VisionBenefits;
DROP TABLE pr2.DentalBenefits;
DROP TABLE pr2.JobInformation;
DROP TABLE pr2.Employees;
DROP TABLE pr2.Courses;
DROP TABLE pr2.Prerequisites;
DROP TABLE pr2.Semester;
DROP TABLE pr2.SemesterInfo;
DROP TABLE pr2.BuildingName;
DROP TABLE pr2.Location;
DROP TABLE pr2.Projector;
DROP TABLE pr2.Classroom;
DROP TABLE pr2.ScheduledCourses;
DROP TABLE pr2.DailyCourseDay;
DROP TABLE pr2.EnrollmentStatus;
DROP TABLE pr2.StudentGrade;
DROP TABLE pr2.Enrollment;